#!/bin/bash

mkdir -p build
cd build
if [ ! -e cmake-3.9.0-rc2-Linux-x86_64.tar.gz ]; then
  wget https://cmake.org/files/v3.9/cmake-3.9.0-rc2-Linux-x86_64.tar.gz
fi
tar -xf cmake-3.9.0-rc2-Linux-x86_64.tar.gz
mv cmake-3.9.0-rc2-Linux-x86_64 cmake
export PATH=`pwd`/cmake/bin:$PATH
./cmake/bin/cmake candy -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Release -DCANDY_ENABLE_STATIC_LINKING=ON -DCANDY_DISABLE_RTTI=ON ..
make candy
cp candy ../bin

