#!/bin/bash

./candy -verb=0 -model -certified -certified-output=$2/proof.out -gate-patterns -no-gate-semantic -rsil-enable -rsil-min-gate-frac=0.7 -rsil-only-miters -gate-timeout=30 -rs-time-limit=60 -rsil-mode=vanishing -rsil-van-halflife=100000000 -rs-rounds=131072 -rs-abort-by-rrat -rs-rrat=0.0005 -rs-max-conj-size=2 $1
